version: '3.9'

services:
  path_traversal_sftp:
    image: atmoz/sftp
    container_name: path_traversal_sftp
    volumes:
      - ./ssh/id_rsa_key.pub:/home/${SFTP_USERNAME:-sftp-user}/.ssh/keys/id_rsa_key.pub:ro
      - ./upload:/home/${SFTP_USERNAME:-sftp-user}/upload
    ports:
      - "2222:22"
    command: ${SFTP_USERNAME:-sftp-user}::1001
  path_traversal_db:
    image: postgres:14.0
    container_name: path_traversal_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 1s
        timeout: 1s
        retries: 5
  path_traversal_backend:
    image: path_traversal_backend
    container_name: path_traversal_backend
    environment:
      - SECRET_KEY=${SECRET_KEY:-insecure-secret-key}
      - SFTP_SALT=${SFTP_SALT:-insecure-sftp-salt}
      - SFTP_SECRET=${SFTP_SECRET:-insecure-sftp-secret}
      - DEBUG=${DEBUG:-true}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-path_traversal_db}
      - DB_PORT=${DB_PORT:-5432}
      - SFTP_BASE_DIR=${SFTP_BASE_DIR:-/upload/}
      - SFTP_HOSTNAME=${SFTP_HOSTNAME:-path_traversal_sftp}
      - SFTP_PORT=${SFTP_PORT:-22}
      - SFTP_USERNAME=${SFTP_USERNAME:-sftp-user}
    volumes:
      - ./path_traversal:/code
    ports:
      - '8000:8000'
    command: bash -c 'python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      path_traversal_db:
        condition: service_healthy
